DROP INDEX IF EXISTS idx_users_id;
DROP INDEX IF EXISTS idx_users_phone_number;
DROP INDEX IF EXISTS idx_products_id;
DROP INDEX IF EXISTS idx_customer_id;
DROP INDEX IF EXISTS idx_customer_phone_number;
DROP INDEX IF EXISTS idx_orders_id;
DROP INDEX IF EXISTS idx_orders_customer_id;
DROP INDEX IF EXISTS idx_order_details_order_id;
DROP INDEX IF EXISTS idx_order_details_product_id;